'use client';

import React from 'react';
import langgraphClient from '@/lib/langgraphClient';
import { WORKFLOW_STEPS } from '@/lib/constants/steps';

export function StepWorkspace({ onContinue, sessionId }: { onContinue: (data: Record<string, string>) => void; sessionId: string | null }) {
  const [workflowState, setWorkflowState] = React.useState<any>(null);

  React.useEffect(() => {
    if (!sessionId) return;
    
    const pollStatus = async () => {
      try {
        const status = await langgraphClient.getWorkflowStatus(sessionId);
        setWorkflowState(status);
      } catch (error) {
        console.warn('Failed to get workflow status:', error);
      }
    };
    
    pollStatus();
    const interval = setInterval(pollStatus, 5000); // Poll every 5 seconds
    return () => clearInterval(interval);
  }, [sessionId]);

  const step = workflowState ? { id: workflowState.stage, name: workflowState.stage, requiredData: [] } : null;
  const state = workflowState || { stepData: {} };

  const requiredKeys = step?.requiredData ?? [];
  const [values, setValues] = React.useState<Record<string, string>>(() => {
    const initial: Record<string, string> = {};
    requiredKeys.forEach((k) => {
      const v = (state.stepData as any)[k];
      initial[k] = typeof v === 'string' ? v : '';
    });
    return initial;
  });
  const [errors, setErrors] = React.useState<string[]>([]);

  React.useEffect(() => {
    // When step changes, reset form based on new required keys
    const fresh: Record<string, string> = {};
    (step?.requiredData ?? []).forEach((k) => {
      const v = (state.stepData as any)[k];
      fresh[k] = typeof v === 'string' ? v : '';
    });
    setValues(fresh);
    setErrors([]);
  }, [step?.id]);

  if (!step) return null;

  const labelFor = (key: string) => key.replace(/_/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/\b\w/g, (m) => m.toUpperCase());
      const isCapture = step?.id === WORKFLOW_STEPS.PROBLEM_CAPTURE;
  const isValid = isCapture ? requiredKeys.every((k) => (values[k] || '').trim().length > 0) : true;

  const handleNext = () => {
    if (!isCapture) return;
    const missing = requiredKeys.filter((k) => !(values[k] || '').trim());
    if (missing.length) {
      setErrors(missing);
      return;
    }
    onContinue(values);
  };

  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="grid grid-cols-1 gap-6">
        {/* Inputs */}
        <div className="bg-white dark:bg-gray-800 border dark:border-gray-700 rounded-lg p-5">
          <div className="text-xl font-semibold mb-1">{step.name}</div>
          {isCapture ? (
            <>
              <div className="text-xs text-gray-500 dark:text-gray-400 mb-4">All required fields must be filled to continue.</div>
              {errors.length > 0 && (
                <div className="mb-4 text-sm text-red-600 dark:text-red-400">
                  Please complete: {errors.map(labelFor).join(', ')}
                </div>
              )}
              <div className="space-y-4">
                {requiredKeys.map((key) => (
                  <div key={key}>
                    <div className="text-sm font-medium mb-2">{labelFor(key)}</div>
                    <textarea
                      rows={key.toLowerCase().includes('timeline') ? 2 : 4}
                      value={values[key] || ''}
                      onChange={(e) => setValues((prev) => ({ ...prev, [key]: e.target.value }))}
                      placeholder={`Enter ${labelFor(key).toLowerCase()}`}
                      className={`w-full px-3 py-2 rounded border dark:border-gray-700 bg-white dark:bg-gray-900 ${errors.includes(key) ? 'border-red-500' : ''}`}
                    />
                  </div>
                ))}
              </div>
              <div className="mt-6">
                <button onClick={handleNext} disabled={!isValid} className="px-5 py-2 rounded bg-indigo-600 text-white disabled:opacity-50">Start Discussion</button>
              </div>
            </>
          ) : (
            <>
              <div className="text-xs text-gray-500 dark:text-gray-400 mb-4">Outputs below are populated by virtual agents after discussion.</div>
              <div className="space-y-4">
                {requiredKeys.map((key) => (
                  <div key={key}>
                    <div className="text-sm font-medium mb-1">{labelFor(key)}</div>
                    <div className="text-sm rounded border dark:border-gray-700 bg-gray-50 dark:bg-gray-900 p-3 min-h-[3.5rem]">
                      {(state.stepData as any)[key] || <span className="text-gray-400">Pending — will be generated by agents</span>}
                    </div>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
        {/* No right column: chat side-panel handles insights */}
      </div>
    </div>
  );
}


