export const WORKFLOW_STEPS = {
  PROBLEM_CAPTURE: 'PROBLEM_CAPTURE',
  PROBLEM_CLARIFICATION: 'PROBLEM_CLARIFICATION',
  SOLUTION_BRAINSTORM: 'SOLUTION_BRAINSTORM',
  COMPETITOR_ANALYSIS: 'COMPETITOR_ANALYSIS',
  SCA_ANALYSIS: 'SCA_ANALYSIS',
  MVP_PLANNING: 'MVP_PLANNING',
  TASK_GENERATION: 'TASK_GENERATION',
} as const;

export const STEP_ORDER = [
  WORKFLOW_STEPS.PROBLEM_CAPTURE,
  WORKFLOW_STEPS.PROBLEM_CLARIFICATION,
  WORKFLOW_STEPS.SOLUTION_BRAINSTORM,
  WORKFLOW_STEPS.COMPETITOR_ANALYSIS,
  WORKFLOW_STEPS.SCA_ANALYSIS,
  WORKFLOW_STEPS.MVP_PLANNING,
  WORKFLOW_STEPS.TASK_GENERATION,
] as const;

export type WorkflowStep = typeof WORKFLOW_STEPS[keyof typeof WORKFLOW_STEPS];